### PR TITLE
refactor: move structs to objects.go, introduce enums, rename variables

### PR DESCRIPTION
**Pull request by graves501**
Hi,

here's another small-ish refactor.

Main points:
* Move all `structs` into `objects.go`
* Introduce some constants/enums in `enums.go`
* Rename quite a few variables (mostly the ones used in the structs) to make the code easier to read and understand

The next few commits/changes will be to rename even more, so the naming of the variables in the code base is more streamlined/consistent.

One question I have:
There were quite a few `crect` and `carect` variables - I did find out that `crect` is the `collisionRectangle`, but what is `carect` supposed to mean?

BR

graves

### CODE REVIEW

**Comment by unklnik** [comment]
OK, I will take a look tomorrow and build it this time before I merge so give me about 12 hours (it is 23:00 here I live in Cape Town, South Africa). If it builds and runs then will merge tomorrow. OK, so when 2 objects collide the crect is when the rectangles of the displayed images collide. The carect is CollisionAreaRectange. So, this is used to detect if one rectangle (object on screen) is in within the collision area of another rectangle. This is used for lets say a bomb explodes on screen then you want to check if the player rectangle collides with the CollisionArea rectangle of the bomb explosion radius.

**Comment by unklnik** [comment]
This image explains it better 

image

**Comment by graves501** [comment]
Hi, thanks for the quick reply! 

Thank you for the visualization and explanation, now it's pretty clear, what you mean!

Also there's no need to hurry, I don't want you or me to get burned out by this endeavor. This is just for fun after all :)
I won't send you 5 PRs per week, I will just browse through the source code every once in a while!

Also it's kinda funny that we're in the same timezone since it's the same here in Austria!

Good night!

BR

graves

**Comment by unklnik** [comment]
Don't worry I know the code well so it is quick for me. So send PRs
whenever it is just that Go is not installed on my pc at the moment so will
need to set up tomorrow

**Comment by unklnik** [comment]
OK merged, I had some time this morning to install Go and built and ran, it seems to work fine, though only checked for a few minutes. I am happy for you to do whatever you want really as long as the game works and other people can also download and build the code. Just give me a short summary of whatever you change when you do a PR so I know what is happening.

You can send as many PRs as you like.

BTW I have actually been to Austria many years ago and was a very nice country

**Pull request merged**
