### PR TITLE
refactor: refactor and move helper functions into helper.go, rename some functions

### PR DESCRIPTION
**Pull request by graves501**
Hi, 

just wanted to congratulate you on finishing a project. You've obviously put a lot of time and effort into this.

I stumbled into your code base by accident, when I saw your Reddit post about releasing a Rogue-like game.
It's funny because I was just reading this Reddit thread about compiling the original Rogue and was also reading the source code for another classic Rogue-like called NetHack. And for whatever reason your thread was in the suggestions.

I've been looking for an excuse to learn/read/write Golang code and thought your repo is super interesting.
It's obviously a huge project that could be split into smaller files.

Maybe we could refactor your game together? It's definitely easier to debug once you split the code base into smaller pieces and remove some code smells like magic numbers and using constants over strings that are used all over the place.

I refactored some of the helper functions and renamed them like `getabs()` to `Abs()` etc. and made the `FlipCoin()` function more performant (at least according to Google and ChatGPT).

And yeah, you have to run `go run .` instead of `go run main.go`.

If you don't feel like changing anything anymore for this game, I do understand. It's a big pile of code. However, I might refactor some things down the line and create some PRs if you don't mind.

BR

graves

### CODE REVIEW

**Comment by unklnik** [comment]
Thanks, this is a good idea. I taught myself to code and the code is very messy and should be in smaller files as it is more manageable. Unfortunately this was just a hobby project and due to work commitments I don't have time to work on it myself so please go ahead.

I am assuming you have tested this and it is working? I will trust you and go ahead and merge

**Comment by graves501** [comment]
@unklnik 

Hi, thanks for your open-mindedness!

Yes, I did compile and run the game for a bit, but I did not do any in-depth testing since I just got started with the code base and therefore also barely played the game itself. It seems to run fine though. 

But in general, I'd advise against randomly merging some random person's PR without testing :grin: 

Anyways, I'd like to continue going through the code base, refactoring small bits and pieces and will therefore open smaller PRs instead of a huge one. This makes the changes also easier to comprehend.

This is also just a hobby thing - I'd learn/write/read Golang code, get to know Raylib and your game a bit and you'd benefit from more readable code I guess :grin: 

I won't promise that I will refactor the whole code base though :sweat_smile:  
Just small pieces here and there - it's not much, but something!

BR

graves

**Comment by unklnik** [comment]
OK I am taking a break from coding/Go/game dev for the moment so won't be helping however go right ahead. And yes, definitely should be testing, will definitely build the next PR and test

**Comment by unklnik** [comment]
BTW I have tried this on other projects after this, breaking code into smaller files. The main.go file can be made considerably smaller quite easily, the problem is that the code structure is quite erratic so you will probably have to spend a lot of time going through it all. If you are going through it the MARK: text is for a Visual Studio Code plugin called Mark Jump that allows you to easily jump between the different points in code. Most things with MARK: in front of them would be the start of sections with the following code functions all (usually) being related. Therefore these could be used as a guide/starting point for splitting into smaller sections.

**Pull request merged**
